
# name: Deploy

# on:
#   push:
#     branches: [ "main" ]

# jobs:
#   deploy:

#     runs-on: ubuntu-latest


#     steps:
#     - uses: actions/checkout@v4
#     - run: docker build . -t harishneel/next-js-app
#     - run: echo "${{secrets.DOCKERHUB_PASSWORD}}" | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin 
#     - run: docker push harishneel/next-js-app:latest

name : Deployment/ Release
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: build docker
        run: docker build . -t bizmail389/githubactions
      - run: echo "${{secrets.DOCKER_TOKEN}}" | docker login -u "${{secrets.DOCKER_USER}}" --password-stdin
      - run: docker push bizmail389/githubactions:latest
