name: Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main]

jobs:
    build:
      runs-on: ubuntu-latest
      
      strategy:
        matrix:
          node-version: [18.x, 20.x, 22.x]
      steps:
        - uses: actions/checkout@v4
        - name: setp the nodejs
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}
            cache: npm
        - name: install dependencies
          run: npm i
        - name: build command.
          run: npm run build

    run-tests:
      needs: build
      runs-on: ubuntu-latest

      strategy:
        matrix:
          node-version: [ 18.x, 20.x, 22.x ]
      
      steps:
        - uses: actions/checkout@v4
        - name: setp the nodejs
          uses: actions/setup-node@v3
          with:
            node-version: ${{matrix.node-version}}
            cache: npm
        - name: install dependencies
          run: npm install
        - name: run the tests
          run: npm test


    
    