# The name 
name: Node.js CI

# on the push & pull_request, the jobs we will be performing . 
# and it used indentation
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# jobs block we can have multiple jobs as there in build (build is just a name ) block ther is only one. 
jobs:
  build:
    # as we have to specify where should it run so in github servers we have specified the machines. 
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    # These are the steps to completly execute the.
    steps:
    # telling github to checkout in github branch .
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
    # It tells that setup the node appl without doing anything.
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        # check package.json

    - run: npm i
    - run: npm run build

  unit-tests:
    
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
       
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm i
    - run: npm run test
