name: Integration

on:
  push: # these are the things on which the job will be performed
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4 #tells github ot check the feature branch by default its to the main branch
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4 #this line is telling github to set the node environment for the project
        with:
          node-version: ${{ matrix.node-version }} #reference to the strategy block
          cache: "npm"

      - name: "Installing dependancies"
        run: npm i

      - name: "Build command"
        run: npm run build

  unit-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4 #tells github ot check the feature branch by default its to the main branch
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4 #this line is telling github to set the node environment for the project
        with:
          node-version: ${{ matrix.node-version }} #reference to the strategy block
          cache: "npm"

      - name: "Installing dependancies"
        run: npm i

      - name: "Running test cases"
        run: npm run test
